package com.bdtrip.mobile.activity.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ActivityScreenEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.screen_id
     *
     * @mbggenerated
     */
    private Integer screenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.scr_date
     *
     * @mbggenerated
     */
    private String scrDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.scr_time
     *
     * @mbggenerated
     */
    private String scrTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.person_num
     *
     * @mbggenerated
     */
    private Integer personNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_screen.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.screen_id
     *
     * @return the value of bd_activity_screen.screen_id
     *
     * @mbggenerated
     */
    public Integer getScreenId() {
        return screenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.screen_id
     *
     * @param screenId the value for bd_activity_screen.screen_id
     *
     * @mbggenerated
     */
    public void setScreenId(Integer screenId) {
        this.screenId = screenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.activity_id
     *
     * @return the value of bd_activity_screen.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.activity_id
     *
     * @param activityId the value for bd_activity_screen.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.scr_date
     *
     * @return the value of bd_activity_screen.scr_date
     *
     * @mbggenerated
     */
    public String getScrDate() {
        return scrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.scr_date
     *
     * @param scrDate the value for bd_activity_screen.scr_date
     *
     * @mbggenerated
     */
    public void setScrDate(String scrDate) {
        this.scrDate = scrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.scr_time
     *
     * @return the value of bd_activity_screen.scr_time
     *
     * @mbggenerated
     */
    public String getScrTime() {
        return scrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.scr_time
     *
     * @param scrTime the value for bd_activity_screen.scr_time
     *
     * @mbggenerated
     */
    public void setScrTime(String scrTime) {
        this.scrTime = scrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.price
     *
     * @return the value of bd_activity_screen.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.price
     *
     * @param price the value for bd_activity_screen.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.person_num
     *
     * @return the value of bd_activity_screen.person_num
     *
     * @mbggenerated
     */
    public Integer getPersonNum() {
        return personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.person_num
     *
     * @param personNum the value for bd_activity_screen.person_num
     *
     * @mbggenerated
     */
    public void setPersonNum(Integer personNum) {
        this.personNum = personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.status
     *
     * @return the value of bd_activity_screen.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.status
     *
     * @param status the value for bd_activity_screen.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.create_by
     *
     * @return the value of bd_activity_screen.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.create_by
     *
     * @param createBy the value for bd_activity_screen.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.create_time
     *
     * @return the value of bd_activity_screen.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.create_time
     *
     * @param createTime the value for bd_activity_screen.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.update_by
     *
     * @return the value of bd_activity_screen.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.update_by
     *
     * @param updateBy the value for bd_activity_screen.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.update_time
     *
     * @return the value of bd_activity_screen.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.update_time
     *
     * @param updateTime the value for bd_activity_screen.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_screen.deleted
     *
     * @return the value of bd_activity_screen.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_screen.deleted
     *
     * @param deleted the value for bd_activity_screen.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}