package com.bdtrip.mobile.activity.entity;

import java.util.Date;

public class ActivityInfoEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.suggest
     *
     * @mbggenerated
     */
    private String suggest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.head_img
     *
     * @mbggenerated
     */
    private String headImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.tbl_img
     *
     * @mbggenerated
     */
    private String tblImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.can_refund
     *
     * @mbggenerated
     */
    private Integer canRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.hour_refund
     *
     * @mbggenerated
     */
    private Integer hourRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.stadium
     *
     * @mbggenerated
     */
    private String stadium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.range_time
     *
     * @mbggenerated
     */
    private String rangeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.online_status
     *
     * @mbggenerated
     */
    private Integer onlineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.audit_status
     *
     * @mbggenerated
     */
    private Integer auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_activity_info.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.activity_id
     *
     * @return the value of bd_activity_info.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.activity_id
     *
     * @param activityId the value for bd_activity_info.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.title
     *
     * @return the value of bd_activity_info.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.title
     *
     * @param title the value for bd_activity_info.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.category
     *
     * @return the value of bd_activity_info.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.category
     *
     * @param category the value for bd_activity_info.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.suggest
     *
     * @return the value of bd_activity_info.suggest
     *
     * @mbggenerated
     */
    public String getSuggest() {
        return suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.suggest
     *
     * @param suggest the value for bd_activity_info.suggest
     *
     * @mbggenerated
     */
    public void setSuggest(String suggest) {
        this.suggest = suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.head_img
     *
     * @return the value of bd_activity_info.head_img
     *
     * @mbggenerated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.head_img
     *
     * @param headImg the value for bd_activity_info.head_img
     *
     * @mbggenerated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.tbl_img
     *
     * @return the value of bd_activity_info.tbl_img
     *
     * @mbggenerated
     */
    public String getTblImg() {
        return tblImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.tbl_img
     *
     * @param tblImg the value for bd_activity_info.tbl_img
     *
     * @mbggenerated
     */
    public void setTblImg(String tblImg) {
        this.tblImg = tblImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.can_refund
     *
     * @return the value of bd_activity_info.can_refund
     *
     * @mbggenerated
     */
    public Integer getCanRefund() {
        return canRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.can_refund
     *
     * @param canRefund the value for bd_activity_info.can_refund
     *
     * @mbggenerated
     */
    public void setCanRefund(Integer canRefund) {
        this.canRefund = canRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.hour_refund
     *
     * @return the value of bd_activity_info.hour_refund
     *
     * @mbggenerated
     */
    public Integer getHourRefund() {
        return hourRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.hour_refund
     *
     * @param hourRefund the value for bd_activity_info.hour_refund
     *
     * @mbggenerated
     */
    public void setHourRefund(Integer hourRefund) {
        this.hourRefund = hourRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.price
     *
     * @return the value of bd_activity_info.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.price
     *
     * @param price the value for bd_activity_info.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.stadium
     *
     * @return the value of bd_activity_info.stadium
     *
     * @mbggenerated
     */
    public String getStadium() {
        return stadium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.stadium
     *
     * @param stadium the value for bd_activity_info.stadium
     *
     * @mbggenerated
     */
    public void setStadium(String stadium) {
        this.stadium = stadium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.address
     *
     * @return the value of bd_activity_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.address
     *
     * @param address the value for bd_activity_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.longitude
     *
     * @return the value of bd_activity_info.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.longitude
     *
     * @param longitude the value for bd_activity_info.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.latitude
     *
     * @return the value of bd_activity_info.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.latitude
     *
     * @param latitude the value for bd_activity_info.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.tel
     *
     * @return the value of bd_activity_info.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.tel
     *
     * @param tel the value for bd_activity_info.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.range_time
     *
     * @return the value of bd_activity_info.range_time
     *
     * @mbggenerated
     */
    public String getRangeTime() {
        return rangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.range_time
     *
     * @param rangeTime the value for bd_activity_info.range_time
     *
     * @mbggenerated
     */
    public void setRangeTime(String rangeTime) {
        this.rangeTime = rangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.online_status
     *
     * @return the value of bd_activity_info.online_status
     *
     * @mbggenerated
     */
    public Integer getOnlineStatus() {
        return onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.online_status
     *
     * @param onlineStatus the value for bd_activity_info.online_status
     *
     * @mbggenerated
     */
    public void setOnlineStatus(Integer onlineStatus) {
        this.onlineStatus = onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.audit_status
     *
     * @return the value of bd_activity_info.audit_status
     *
     * @mbggenerated
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.audit_status
     *
     * @param auditStatus the value for bd_activity_info.audit_status
     *
     * @mbggenerated
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.create_by
     *
     * @return the value of bd_activity_info.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.create_by
     *
     * @param createBy the value for bd_activity_info.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.create_time
     *
     * @return the value of bd_activity_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.create_time
     *
     * @param createTime the value for bd_activity_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.update_by
     *
     * @return the value of bd_activity_info.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.update_by
     *
     * @param updateBy the value for bd_activity_info.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.update_time
     *
     * @return the value of bd_activity_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.update_time
     *
     * @param updateTime the value for bd_activity_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_activity_info.deleted
     *
     * @return the value of bd_activity_info.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_activity_info.deleted
     *
     * @param deleted the value for bd_activity_info.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}