mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://192.168.223.128:3306/e3mall
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    solr:
      host: http://192.168.223.128:8983/solr/collection1
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.223.128:61616
    pool:
      enabled: true
      max-connections: 50
    packages:
      trust-all: false

dubbo:
  application:
    name: e3-search
  registry:
    address: zookeeper://192.168.223.128:2181
  scan:
    basePackages: guo.ping.e3mall.search.service
  protocol:
    port: 20882