package com.bdtrip.mobile.activity.dao;

import com.bdtrip.mobile.activity.entity.ActivityContentEntity;
import com.bdtrip.mobile.activity.entity.ActivityContentEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ActivityContentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    int countByExample(ActivityContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    int deleteByExample(ActivityContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_activity_content",
        "where content_id = #{contentId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_activity_content (activity_id, content_type, ",
        "status, create_by, ",
        "create_time, update_by, ",
        "update_time, deleted, ",
        "content)",
        "values (#{activityId,jdbcType=INTEGER}, #{contentType,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=VARCHAR}, #{createBy,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleted,jdbcType=INTEGER}, ",
        "#{content,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="contentId", before=false, resultType=Integer.class)
    int insert(ActivityContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    int insertSelective(ActivityContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    List<ActivityContentEntity> selectByExampleWithBLOBs(ActivityContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    List<ActivityContentEntity> selectByExample(ActivityContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "content_id, activity_id, content_type, status, create_by, create_time, update_by, ",
        "update_time, deleted, content",
        "from bd_activity_content",
        "where content_id = #{contentId,jdbcType=INTEGER}"
    })
    @ResultMap("com.bdtrip.mobile.activity.dao.ActivityContentEntityMapper.ResultMapWithBLOBs")
    ActivityContentEntity selectByPrimaryKey(Integer contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActivityContentEntity record, @Param("example") ActivityContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ActivityContentEntity record, @Param("example") ActivityContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActivityContentEntity record, @Param("example") ActivityContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    @Update({
        "update bd_activity_content",
        "set activity_id = #{activityId,jdbcType=INTEGER},",
          "content_type = #{contentType,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER},",
          "content = #{content,jdbcType=LONGVARCHAR}",
        "where content_id = #{contentId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(ActivityContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content
     *
     * @mbggenerated
     */
    @Update({
        "update bd_activity_content",
        "set activity_id = #{activityId,jdbcType=INTEGER},",
          "content_type = #{contentType,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where content_id = #{contentId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ActivityContentEntity record);
}