package com.bdtrip.mobile.activity.dao;

import com.bdtrip.mobile.activity.entity.ActivityInfoEntity;
import com.bdtrip.mobile.activity.entity.ActivityInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ActivityInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    int countByExample(ActivityInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    int deleteByExample(ActivityInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_activity_info",
        "where activity_id = #{activityId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_activity_info (title, category, ",
        "suggest, head_img, ",
        "tbl_img, can_refund, ",
        "hour_refund, price, ",
        "stadium, address, ",
        "longitude, latitude, ",
        "tel, range_time, ",
        "online_status, audit_status, ",
        "create_by, create_time, ",
        "update_by, update_time, ",
        "deleted)",
        "values (#{title,jdbcType=VARCHAR}, #{category,jdbcType=INTEGER}, ",
        "#{suggest,jdbcType=VARCHAR}, #{headImg,jdbcType=VARCHAR}, ",
        "#{tblImg,jdbcType=VARCHAR}, #{canRefund,jdbcType=INTEGER}, ",
        "#{hourRefund,jdbcType=INTEGER}, #{price,jdbcType=VARCHAR}, ",
        "#{stadium,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{longitude,jdbcType=VARCHAR}, #{latitude,jdbcType=VARCHAR}, ",
        "#{tel,jdbcType=VARCHAR}, #{rangeTime,jdbcType=VARCHAR}, ",
        "#{onlineStatus,jdbcType=INTEGER}, #{auditStatus,jdbcType=INTEGER}, ",
        "#{createBy,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{deleted,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="activityId", before=false, resultType=Integer.class)
    int insert(ActivityInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    int insertSelective(ActivityInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    List<ActivityInfoEntity> selectByExample(ActivityInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "activity_id, title, category, suggest, head_img, tbl_img, can_refund, hour_refund, ",
        "price, stadium, address, longitude, latitude, tel, range_time, online_status, ",
        "audit_status, create_by, create_time, update_by, update_time, deleted",
        "from bd_activity_info",
        "where activity_id = #{activityId,jdbcType=INTEGER}"
    })
    @ResultMap("com.bdtrip.mobile.activity.dao.ActivityInfoEntityMapper.BaseResultMap")
    ActivityInfoEntity selectByPrimaryKey(Integer activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActivityInfoEntity record, @Param("example") ActivityInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActivityInfoEntity record, @Param("example") ActivityInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_info
     *
     * @mbggenerated
     */
    @Update({
        "update bd_activity_info",
        "set title = #{title,jdbcType=VARCHAR},",
          "category = #{category,jdbcType=INTEGER},",
          "suggest = #{suggest,jdbcType=VARCHAR},",
          "head_img = #{headImg,jdbcType=VARCHAR},",
          "tbl_img = #{tblImg,jdbcType=VARCHAR},",
          "can_refund = #{canRefund,jdbcType=INTEGER},",
          "hour_refund = #{hourRefund,jdbcType=INTEGER},",
          "price = #{price,jdbcType=VARCHAR},",
          "stadium = #{stadium,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "longitude = #{longitude,jdbcType=VARCHAR},",
          "latitude = #{latitude,jdbcType=VARCHAR},",
          "tel = #{tel,jdbcType=VARCHAR},",
          "range_time = #{rangeTime,jdbcType=VARCHAR},",
          "online_status = #{onlineStatus,jdbcType=INTEGER},",
          "audit_status = #{auditStatus,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where activity_id = #{activityId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ActivityInfoEntity record);
}