package com.bdtrip.mobile.activity.dao;

import com.bdtrip.mobile.activity.entity.ActivityScreenEntity;
import com.bdtrip.mobile.activity.entity.ActivityScreenEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ActivityScreenEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    int countByExample(ActivityScreenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    int deleteByExample(ActivityScreenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_activity_screen",
        "where screen_id = #{screenId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer screenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_activity_screen (activity_id, scr_date, ",
        "scr_time, price, ",
        "person_num, status, ",
        "create_by, create_time, ",
        "update_by, update_time, ",
        "deleted)",
        "values (#{activityId,jdbcType=INTEGER}, #{scrDate,jdbcType=VARCHAR}, ",
        "#{scrTime,jdbcType=VARCHAR}, #{price,jdbcType=DECIMAL}, ",
        "#{personNum,jdbcType=INTEGER}, #{status,jdbcType=INTEGER}, ",
        "#{createBy,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{deleted,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="screenId", before=false, resultType=Integer.class)
    int insert(ActivityScreenEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    int insertSelective(ActivityScreenEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    List<ActivityScreenEntity> selectByExample(ActivityScreenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "screen_id, activity_id, scr_date, scr_time, price, person_num, status, create_by, ",
        "create_time, update_by, update_time, deleted",
        "from bd_activity_screen",
        "where screen_id = #{screenId,jdbcType=INTEGER}"
    })
    @ResultMap("com.bdtrip.mobile.activity.dao.ActivityScreenEntityMapper.BaseResultMap")
    ActivityScreenEntity selectByPrimaryKey(Integer screenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActivityScreenEntity record, @Param("example") ActivityScreenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActivityScreenEntity record, @Param("example") ActivityScreenEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityScreenEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_screen
     *
     * @mbggenerated
     */
    @Update({
        "update bd_activity_screen",
        "set activity_id = #{activityId,jdbcType=INTEGER},",
          "scr_date = #{scrDate,jdbcType=VARCHAR},",
          "scr_time = #{scrTime,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "person_num = #{personNum,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where screen_id = #{screenId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ActivityScreenEntity record);
}