package com.bdtrip.mobile.activity.dao;

import com.bdtrip.mobile.activity.entity.ContentPictrueEntity;
import com.bdtrip.mobile.activity.entity.ContentPictrueEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ContentPictrueEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    int countByExample(ContentPictrueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    int deleteByExample(ContentPictrueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_activity_content_pictrue",
        "where picture_id = #{pictureId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pictureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_activity_content_pictrue (content_id, picture_url, ",
        "create_by, create_time, ",
        "update_by, update_time, ",
        "deleted)",
        "values (#{contentId,jdbcType=INTEGER}, #{pictureUrl,jdbcType=VARCHAR}, ",
        "#{createBy,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{deleted,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="pictureId", before=false, resultType=Integer.class)
    int insert(ContentPictrueEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    int insertSelective(ContentPictrueEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    List<ContentPictrueEntity> selectByExample(ContentPictrueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "picture_id, content_id, picture_url, create_by, create_time, update_by, update_time, ",
        "deleted",
        "from bd_activity_content_pictrue",
        "where picture_id = #{pictureId,jdbcType=INTEGER}"
    })
    @ResultMap("com.bdtrip.mobile.activity.dao.ContentPictrueEntityMapper.BaseResultMap")
    ContentPictrueEntity selectByPrimaryKey(Integer pictureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ContentPictrueEntity record, @Param("example") ContentPictrueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ContentPictrueEntity record, @Param("example") ContentPictrueEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ContentPictrueEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_activity_content_pictrue
     *
     * @mbggenerated
     */
    @Update({
        "update bd_activity_content_pictrue",
        "set content_id = #{contentId,jdbcType=INTEGER},",
          "picture_url = #{pictureUrl,jdbcType=VARCHAR},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where picture_id = #{pictureId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ContentPictrueEntity record);
}