package com.bdtrip.mobile.line.dao;

import com.bdtrip.mobile.line.entity.LineTripContentEntity;
import com.bdtrip.mobile.line.entity.LineTripContentEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface LineTripContentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    int countByExample(LineTripContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    int deleteByExample(LineTripContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_business_line_trip_content",
        "where content_id = #{contentId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_business_line_trip_content (trip_id, subtitle, ",
        "pic_template, content_type, ",
        "create_by, create_time, ",
        "update_by, update_time, ",
        "deleted, trip_content)",
        "values (#{tripId,jdbcType=BIGINT}, #{subtitle,jdbcType=VARCHAR}, ",
        "#{picTemplate,jdbcType=INTEGER}, #{contentType,jdbcType=INTEGER}, ",
        "#{createBy,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{deleted,jdbcType=INTEGER}, #{tripContent,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="contentId", before=false, resultType=Long.class)
    int insert(LineTripContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    int insertSelective(LineTripContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    List<LineTripContentEntity> selectByExampleWithBLOBs(LineTripContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    List<LineTripContentEntity> selectByExample(LineTripContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "content_id, trip_id, subtitle, pic_template, content_type, create_by, create_time, ",
        "update_by, update_time, deleted, trip_content",
        "from bd_business_line_trip_content",
        "where content_id = #{contentId,jdbcType=BIGINT}"
    })
    @ResultMap("com.bdtrip.mobile.line.dao.LineTripContentEntityMapper.ResultMapWithBLOBs")
    LineTripContentEntity selectByPrimaryKey(Long contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LineTripContentEntity record, @Param("example") LineTripContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") LineTripContentEntity record, @Param("example") LineTripContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LineTripContentEntity record, @Param("example") LineTripContentEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LineTripContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    @Update({
        "update bd_business_line_trip_content",
        "set trip_id = #{tripId,jdbcType=BIGINT},",
          "subtitle = #{subtitle,jdbcType=VARCHAR},",
          "pic_template = #{picTemplate,jdbcType=INTEGER},",
          "content_type = #{contentType,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER},",
          "trip_content = #{tripContent,jdbcType=LONGVARCHAR}",
        "where content_id = #{contentId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(LineTripContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip_content
     *
     * @mbggenerated
     */
    @Update({
        "update bd_business_line_trip_content",
        "set trip_id = #{tripId,jdbcType=BIGINT},",
          "subtitle = #{subtitle,jdbcType=VARCHAR},",
          "pic_template = #{picTemplate,jdbcType=INTEGER},",
          "content_type = #{contentType,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where content_id = #{contentId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LineTripContentEntity record);
}