package com.bdtrip.mobile.line.dao;

import com.bdtrip.mobile.line.entity.LineInfoEntity;
import com.bdtrip.mobile.line.entity.LineInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface LineInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    int countByExample(LineInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    int deleteByExample(LineInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_business_line_info",
        "where line_id = #{lineId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_business_line_info (line_selling, line_template, ",
        "line_type, travel_type, ",
        "start_place, end_place, ",
        "trip_day, trip_night, ",
        "line_name, feature_type, ",
        "recommend, head_picture, ",
        "thumbnail, subtitle, ",
        "audit_status, online_status, ",
        "create_by, create_time, ",
        "update_by, update_time, ",
        "deleted, feature_content)",
        "values (#{lineSelling,jdbcType=INTEGER}, #{lineTemplate,jdbcType=INTEGER}, ",
        "#{lineType,jdbcType=INTEGER}, #{travelType,jdbcType=INTEGER}, ",
        "#{startPlace,jdbcType=VARCHAR}, #{endPlace,jdbcType=VARCHAR}, ",
        "#{tripDay,jdbcType=INTEGER}, #{tripNight,jdbcType=INTEGER}, ",
        "#{lineName,jdbcType=VARCHAR}, #{featureType,jdbcType=INTEGER}, ",
        "#{recommend,jdbcType=INTEGER}, #{headPicture,jdbcType=VARCHAR}, ",
        "#{thumbnail,jdbcType=VARCHAR}, #{subtitle,jdbcType=VARCHAR}, ",
        "#{auditStatus,jdbcType=INTEGER}, #{onlineStatus,jdbcType=INTEGER}, ",
        "#{createBy,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{deleted,jdbcType=INTEGER}, #{featureContent,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="lineId", before=false, resultType=Long.class)
    int insert(LineInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    int insertSelective(LineInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    List<LineInfoEntity> selectByExampleWithBLOBs(LineInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    List<LineInfoEntity> selectByExample(LineInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "line_id, line_selling, line_template, line_type, travel_type, start_place, end_place, ",
        "trip_day, trip_night, line_name, feature_type, recommend, head_picture, thumbnail, ",
        "subtitle, audit_status, online_status, create_by, create_time, update_by, update_time, ",
        "deleted, feature_content",
        "from bd_business_line_info",
        "where line_id = #{lineId,jdbcType=BIGINT}"
    })
    @ResultMap("com.bdtrip.mobile.line.dao.LineInfoEntityMapper.ResultMapWithBLOBs")
    LineInfoEntity selectByPrimaryKey(Long lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LineInfoEntity record, @Param("example") LineInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") LineInfoEntity record, @Param("example") LineInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LineInfoEntity record, @Param("example") LineInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LineInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    @Update({
        "update bd_business_line_info",
        "set line_selling = #{lineSelling,jdbcType=INTEGER},",
          "line_template = #{lineTemplate,jdbcType=INTEGER},",
          "line_type = #{lineType,jdbcType=INTEGER},",
          "travel_type = #{travelType,jdbcType=INTEGER},",
          "start_place = #{startPlace,jdbcType=VARCHAR},",
          "end_place = #{endPlace,jdbcType=VARCHAR},",
          "trip_day = #{tripDay,jdbcType=INTEGER},",
          "trip_night = #{tripNight,jdbcType=INTEGER},",
          "line_name = #{lineName,jdbcType=VARCHAR},",
          "feature_type = #{featureType,jdbcType=INTEGER},",
          "recommend = #{recommend,jdbcType=INTEGER},",
          "head_picture = #{headPicture,jdbcType=VARCHAR},",
          "thumbnail = #{thumbnail,jdbcType=VARCHAR},",
          "subtitle = #{subtitle,jdbcType=VARCHAR},",
          "audit_status = #{auditStatus,jdbcType=INTEGER},",
          "online_status = #{onlineStatus,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER},",
          "feature_content = #{featureContent,jdbcType=LONGVARCHAR}",
        "where line_id = #{lineId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(LineInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    @Update({
        "update bd_business_line_info",
        "set line_selling = #{lineSelling,jdbcType=INTEGER},",
          "line_template = #{lineTemplate,jdbcType=INTEGER},",
          "line_type = #{lineType,jdbcType=INTEGER},",
          "travel_type = #{travelType,jdbcType=INTEGER},",
          "start_place = #{startPlace,jdbcType=VARCHAR},",
          "end_place = #{endPlace,jdbcType=VARCHAR},",
          "trip_day = #{tripDay,jdbcType=INTEGER},",
          "trip_night = #{tripNight,jdbcType=INTEGER},",
          "line_name = #{lineName,jdbcType=VARCHAR},",
          "feature_type = #{featureType,jdbcType=INTEGER},",
          "recommend = #{recommend,jdbcType=INTEGER},",
          "head_picture = #{headPicture,jdbcType=VARCHAR},",
          "thumbnail = #{thumbnail,jdbcType=VARCHAR},",
          "subtitle = #{subtitle,jdbcType=VARCHAR},",
          "audit_status = #{auditStatus,jdbcType=INTEGER},",
          "online_status = #{onlineStatus,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where line_id = #{lineId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LineInfoEntity record);
}