package com.bdtrip.mobile.line.dao;

import com.bdtrip.mobile.line.entity.LineGroupPriceEntity;
import com.bdtrip.mobile.line.entity.LineGroupPriceEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface LineGroupPriceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    int countByExample(LineGroupPriceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    int deleteByExample(LineGroupPriceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_business_line_group_price",
        "where product_id = #{productId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_business_line_group_price (group_id, send_time, ",
        "adult_price, child_price, ",
        "difference_price, confirm_way, ",
        "stock, schedule_days, ",
        "is_sell, create_by, ",
        "create_time, update_by, ",
        "update_time, deleted)",
        "values (#{groupId,jdbcType=BIGINT}, #{sendTime,jdbcType=VARCHAR}, ",
        "#{adultPrice,jdbcType=DECIMAL}, #{childPrice,jdbcType=DECIMAL}, ",
        "#{differencePrice,jdbcType=DECIMAL}, #{confirmWay,jdbcType=INTEGER}, ",
        "#{stock,jdbcType=INTEGER}, #{scheduleDays,jdbcType=INTEGER}, ",
        "#{isSell,jdbcType=INTEGER}, #{createBy,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleted,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="productId", before=false, resultType=Long.class)
    int insert(LineGroupPriceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    int insertSelective(LineGroupPriceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    List<LineGroupPriceEntity> selectByExample(LineGroupPriceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "product_id, group_id, send_time, adult_price, child_price, difference_price, ",
        "confirm_way, stock, schedule_days, is_sell, create_by, create_time, update_by, ",
        "update_time, deleted",
        "from bd_business_line_group_price",
        "where product_id = #{productId,jdbcType=BIGINT}"
    })
    @ResultMap("com.bdtrip.mobile.line.dao.LineGroupPriceEntityMapper.BaseResultMap")
    LineGroupPriceEntity selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LineGroupPriceEntity record, @Param("example") LineGroupPriceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LineGroupPriceEntity record, @Param("example") LineGroupPriceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LineGroupPriceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_group_price
     *
     * @mbggenerated
     */
    @Update({
        "update bd_business_line_group_price",
        "set group_id = #{groupId,jdbcType=BIGINT},",
          "send_time = #{sendTime,jdbcType=VARCHAR},",
          "adult_price = #{adultPrice,jdbcType=DECIMAL},",
          "child_price = #{childPrice,jdbcType=DECIMAL},",
          "difference_price = #{differencePrice,jdbcType=DECIMAL},",
          "confirm_way = #{confirmWay,jdbcType=INTEGER},",
          "stock = #{stock,jdbcType=INTEGER},",
          "schedule_days = #{scheduleDays,jdbcType=INTEGER},",
          "is_sell = #{isSell,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where product_id = #{productId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LineGroupPriceEntity record);
}