package com.bdtrip.mobile.line.dao;

import com.bdtrip.mobile.line.entity.LineTripEntity;
import com.bdtrip.mobile.line.entity.LineTripEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface LineTripEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    int countByExample(LineTripEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    int deleteByExample(LineTripEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_business_line_trip",
        "where trip_id = #{tripId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long tripId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_business_line_trip (line_id, title, ",
        "traffic, meals, ",
        "hotel_type, hotel_name, ",
        "day, create_by, create_time, ",
        "update_by, update_time, ",
        "deleted)",
        "values (#{lineId,jdbcType=BIGINT}, #{title,jdbcType=VARCHAR}, ",
        "#{traffic,jdbcType=VARCHAR}, #{meals,jdbcType=VARCHAR}, ",
        "#{hotelType,jdbcType=INTEGER}, #{hotelName,jdbcType=VARCHAR}, ",
        "#{day,jdbcType=INTEGER}, #{createBy,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{deleted,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="tripId", before=false, resultType=Long.class)
    int insert(LineTripEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    int insertSelective(LineTripEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    List<LineTripEntity> selectByExample(LineTripEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "trip_id, line_id, title, traffic, meals, hotel_type, hotel_name, day, create_by, ",
        "create_time, update_by, update_time, deleted",
        "from bd_business_line_trip",
        "where trip_id = #{tripId,jdbcType=BIGINT}"
    })
    @ResultMap("com.bdtrip.mobile.line.dao.LineTripEntityMapper.BaseResultMap")
    LineTripEntity selectByPrimaryKey(Long tripId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LineTripEntity record, @Param("example") LineTripEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LineTripEntity record, @Param("example") LineTripEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LineTripEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_trip
     *
     * @mbggenerated
     */
    @Update({
        "update bd_business_line_trip",
        "set line_id = #{lineId,jdbcType=BIGINT},",
          "title = #{title,jdbcType=VARCHAR},",
          "traffic = #{traffic,jdbcType=VARCHAR},",
          "meals = #{meals,jdbcType=VARCHAR},",
          "hotel_type = #{hotelType,jdbcType=INTEGER},",
          "hotel_name = #{hotelName,jdbcType=VARCHAR},",
          "day = #{day,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where trip_id = #{tripId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LineTripEntity record);
}