package com.bdtrip.mobile.line.dao;

import com.bdtrip.mobile.line.entity.LineTagsEntity;
import com.bdtrip.mobile.line.entity.LineTagsEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface LineTagsEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    int countByExample(LineTagsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    int deleteByExample(LineTagsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_business_line_tags",
        "where tags_id = #{tagsId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long tagsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_business_line_tags (line_id, target_type, ",
        "target_value, create_by, ",
        "create_time, update_by, ",
        "update_time, deleted)",
        "values (#{lineId,jdbcType=BIGINT}, #{targetType,jdbcType=INTEGER}, ",
        "#{targetValue,jdbcType=INTEGER}, #{createBy,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleted,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="tagsId", before=false, resultType=Long.class)
    int insert(LineTagsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    int insertSelective(LineTagsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    List<LineTagsEntity> selectByExample(LineTagsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "tags_id, line_id, target_type, target_value, create_by, create_time, update_by, ",
        "update_time, deleted",
        "from bd_business_line_tags",
        "where tags_id = #{tagsId,jdbcType=BIGINT}"
    })
    @ResultMap("com.bdtrip.mobile.line.dao.LineTagsEntityMapper.BaseResultMap")
    LineTagsEntity selectByPrimaryKey(Long tagsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LineTagsEntity record, @Param("example") LineTagsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LineTagsEntity record, @Param("example") LineTagsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LineTagsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_tags
     *
     * @mbggenerated
     */
    @Update({
        "update bd_business_line_tags",
        "set line_id = #{lineId,jdbcType=BIGINT},",
          "target_type = #{targetType,jdbcType=INTEGER},",
          "target_value = #{targetValue,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where tags_id = #{tagsId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LineTagsEntity record);
}