package com.bdtrip.mobile.line.dao;

import com.bdtrip.mobile.line.entity.SupplierInfoEntity;
import com.bdtrip.mobile.line.entity.SupplierInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SupplierInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    int countByExample(SupplierInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    int deleteByExample(SupplierInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_business_supplier_info",
        "where supplier_id = #{supplierId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_business_supplier_info (supplier_name, supplier_type, ",
        "work_time, linkman, ",
        "phone, province, ",
        "city, area, address, ",
        "create_by, create_time, ",
        "update_by, update_time, ",
        "deleted)",
        "values (#{supplierName,jdbcType=VARCHAR}, #{supplierType,jdbcType=VARCHAR}, ",
        "#{workTime,jdbcType=VARCHAR}, #{linkman,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{province,jdbcType=INTEGER}, ",
        "#{city,jdbcType=INTEGER}, #{area,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
        "#{createBy,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=INTEGER}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{deleted,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="supplierId", before=false, resultType=Long.class)
    int insert(SupplierInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    int insertSelective(SupplierInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    List<SupplierInfoEntity> selectByExample(SupplierInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "supplier_id, supplier_name, supplier_type, work_time, linkman, phone, province, ",
        "city, area, address, create_by, create_time, update_by, update_time, deleted",
        "from bd_business_supplier_info",
        "where supplier_id = #{supplierId,jdbcType=BIGINT}"
    })
    @ResultMap("com.bdtrip.mobile.line.dao.SupplierInfoEntityMapper.BaseResultMap")
    SupplierInfoEntity selectByPrimaryKey(Long supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SupplierInfoEntity record, @Param("example") SupplierInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SupplierInfoEntity record, @Param("example") SupplierInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SupplierInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_supplier_info
     *
     * @mbggenerated
     */
    @Update({
        "update bd_business_supplier_info",
        "set supplier_name = #{supplierName,jdbcType=VARCHAR},",
          "supplier_type = #{supplierType,jdbcType=VARCHAR},",
          "work_time = #{workTime,jdbcType=VARCHAR},",
          "linkman = #{linkman,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "province = #{province,jdbcType=INTEGER},",
          "city = #{city,jdbcType=INTEGER},",
          "area = #{area,jdbcType=INTEGER},",
          "address = #{address,jdbcType=VARCHAR},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where supplier_id = #{supplierId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SupplierInfoEntity record);
}