package com.bdtrip.mobile.line.dao;

import com.bdtrip.mobile.line.entity.TripContentPictureEntity;
import com.bdtrip.mobile.line.entity.TripContentPictureEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface TripContentPictureEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    int countByExample(TripContentPictureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    int deleteByExample(TripContentPictureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    @Delete({
        "delete from bd_business_trip_content_pictrue",
        "where picture_id = #{pictureId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long pictureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    @Insert({
        "insert into bd_business_trip_content_pictrue (content_id, picture_url, ",
        "picture_order, create_by, ",
        "create_time, update_by, ",
        "update_time, deleted)",
        "values (#{contentId,jdbcType=BIGINT}, #{pictureUrl,jdbcType=VARCHAR}, ",
        "#{pictureOrder,jdbcType=INTEGER}, #{createBy,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{deleted,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="pictureId", before=false, resultType=Long.class)
    int insert(TripContentPictureEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    int insertSelective(TripContentPictureEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    List<TripContentPictureEntity> selectByExample(TripContentPictureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "picture_id, content_id, picture_url, picture_order, create_by, create_time, ",
        "update_by, update_time, deleted",
        "from bd_business_trip_content_pictrue",
        "where picture_id = #{pictureId,jdbcType=BIGINT}"
    })
    @ResultMap("com.bdtrip.mobile.line.dao.TripContentPictureEntityMapper.BaseResultMap")
    TripContentPictureEntity selectByPrimaryKey(Long pictureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TripContentPictureEntity record, @Param("example") TripContentPictureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TripContentPictureEntity record, @Param("example") TripContentPictureEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TripContentPictureEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_trip_content_pictrue
     *
     * @mbggenerated
     */
    @Update({
        "update bd_business_trip_content_pictrue",
        "set content_id = #{contentId,jdbcType=BIGINT},",
          "picture_url = #{pictureUrl,jdbcType=VARCHAR},",
          "picture_order = #{pictureOrder,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "deleted = #{deleted,jdbcType=INTEGER}",
        "where picture_id = #{pictureId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TripContentPictureEntity record);
}