package com.bdtrip.mobile.line.entity;

import java.math.BigDecimal;
import java.util.Date;

public class LineGroupPriceEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.send_time
     *
     * @mbggenerated
     */
    private String sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.adult_price
     *
     * @mbggenerated
     */
    private BigDecimal adultPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.child_price
     *
     * @mbggenerated
     */
    private BigDecimal childPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.difference_price
     *
     * @mbggenerated
     */
    private BigDecimal differencePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.confirm_way
     *
     * @mbggenerated
     */
    private Integer confirmWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.schedule_days
     *
     * @mbggenerated
     */
    private Integer scheduleDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.is_sell
     *
     * @mbggenerated
     */
    private Integer isSell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_group_price.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.product_id
     *
     * @return the value of bd_business_line_group_price.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.product_id
     *
     * @param productId the value for bd_business_line_group_price.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.group_id
     *
     * @return the value of bd_business_line_group_price.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.group_id
     *
     * @param groupId the value for bd_business_line_group_price.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.send_time
     *
     * @return the value of bd_business_line_group_price.send_time
     *
     * @mbggenerated
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.send_time
     *
     * @param sendTime the value for bd_business_line_group_price.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.adult_price
     *
     * @return the value of bd_business_line_group_price.adult_price
     *
     * @mbggenerated
     */
    public BigDecimal getAdultPrice() {
        return adultPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.adult_price
     *
     * @param adultPrice the value for bd_business_line_group_price.adult_price
     *
     * @mbggenerated
     */
    public void setAdultPrice(BigDecimal adultPrice) {
        this.adultPrice = adultPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.child_price
     *
     * @return the value of bd_business_line_group_price.child_price
     *
     * @mbggenerated
     */
    public BigDecimal getChildPrice() {
        return childPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.child_price
     *
     * @param childPrice the value for bd_business_line_group_price.child_price
     *
     * @mbggenerated
     */
    public void setChildPrice(BigDecimal childPrice) {
        this.childPrice = childPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.difference_price
     *
     * @return the value of bd_business_line_group_price.difference_price
     *
     * @mbggenerated
     */
    public BigDecimal getDifferencePrice() {
        return differencePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.difference_price
     *
     * @param differencePrice the value for bd_business_line_group_price.difference_price
     *
     * @mbggenerated
     */
    public void setDifferencePrice(BigDecimal differencePrice) {
        this.differencePrice = differencePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.confirm_way
     *
     * @return the value of bd_business_line_group_price.confirm_way
     *
     * @mbggenerated
     */
    public Integer getConfirmWay() {
        return confirmWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.confirm_way
     *
     * @param confirmWay the value for bd_business_line_group_price.confirm_way
     *
     * @mbggenerated
     */
    public void setConfirmWay(Integer confirmWay) {
        this.confirmWay = confirmWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.stock
     *
     * @return the value of bd_business_line_group_price.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.stock
     *
     * @param stock the value for bd_business_line_group_price.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.schedule_days
     *
     * @return the value of bd_business_line_group_price.schedule_days
     *
     * @mbggenerated
     */
    public Integer getScheduleDays() {
        return scheduleDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.schedule_days
     *
     * @param scheduleDays the value for bd_business_line_group_price.schedule_days
     *
     * @mbggenerated
     */
    public void setScheduleDays(Integer scheduleDays) {
        this.scheduleDays = scheduleDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.is_sell
     *
     * @return the value of bd_business_line_group_price.is_sell
     *
     * @mbggenerated
     */
    public Integer getIsSell() {
        return isSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.is_sell
     *
     * @param isSell the value for bd_business_line_group_price.is_sell
     *
     * @mbggenerated
     */
    public void setIsSell(Integer isSell) {
        this.isSell = isSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.create_by
     *
     * @return the value of bd_business_line_group_price.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.create_by
     *
     * @param createBy the value for bd_business_line_group_price.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.create_time
     *
     * @return the value of bd_business_line_group_price.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.create_time
     *
     * @param createTime the value for bd_business_line_group_price.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.update_by
     *
     * @return the value of bd_business_line_group_price.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.update_by
     *
     * @param updateBy the value for bd_business_line_group_price.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.update_time
     *
     * @return the value of bd_business_line_group_price.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.update_time
     *
     * @param updateTime the value for bd_business_line_group_price.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_group_price.deleted
     *
     * @return the value of bd_business_line_group_price.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_group_price.deleted
     *
     * @param deleted the value for bd_business_line_group_price.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}