package com.bdtrip.mobile.line.entity;

import java.util.Date;

public class LineTripEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.trip_id
     *
     * @mbggenerated
     */
    private Long tripId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.line_id
     *
     * @mbggenerated
     */
    private Long lineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.traffic
     *
     * @mbggenerated
     */
    private String traffic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.meals
     *
     * @mbggenerated
     */
    private String meals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.hotel_type
     *
     * @mbggenerated
     */
    private Integer hotelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.hotel_name
     *
     * @mbggenerated
     */
    private String hotelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.day
     *
     * @mbggenerated
     */
    private Integer day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.trip_id
     *
     * @return the value of bd_business_line_trip.trip_id
     *
     * @mbggenerated
     */
    public Long getTripId() {
        return tripId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.trip_id
     *
     * @param tripId the value for bd_business_line_trip.trip_id
     *
     * @mbggenerated
     */
    public void setTripId(Long tripId) {
        this.tripId = tripId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.line_id
     *
     * @return the value of bd_business_line_trip.line_id
     *
     * @mbggenerated
     */
    public Long getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.line_id
     *
     * @param lineId the value for bd_business_line_trip.line_id
     *
     * @mbggenerated
     */
    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.title
     *
     * @return the value of bd_business_line_trip.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.title
     *
     * @param title the value for bd_business_line_trip.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.traffic
     *
     * @return the value of bd_business_line_trip.traffic
     *
     * @mbggenerated
     */
    public String getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.traffic
     *
     * @param traffic the value for bd_business_line_trip.traffic
     *
     * @mbggenerated
     */
    public void setTraffic(String traffic) {
        this.traffic = traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.meals
     *
     * @return the value of bd_business_line_trip.meals
     *
     * @mbggenerated
     */
    public String getMeals() {
        return meals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.meals
     *
     * @param meals the value for bd_business_line_trip.meals
     *
     * @mbggenerated
     */
    public void setMeals(String meals) {
        this.meals = meals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.hotel_type
     *
     * @return the value of bd_business_line_trip.hotel_type
     *
     * @mbggenerated
     */
    public Integer getHotelType() {
        return hotelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.hotel_type
     *
     * @param hotelType the value for bd_business_line_trip.hotel_type
     *
     * @mbggenerated
     */
    public void setHotelType(Integer hotelType) {
        this.hotelType = hotelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.hotel_name
     *
     * @return the value of bd_business_line_trip.hotel_name
     *
     * @mbggenerated
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.hotel_name
     *
     * @param hotelName the value for bd_business_line_trip.hotel_name
     *
     * @mbggenerated
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.day
     *
     * @return the value of bd_business_line_trip.day
     *
     * @mbggenerated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.day
     *
     * @param day the value for bd_business_line_trip.day
     *
     * @mbggenerated
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.create_by
     *
     * @return the value of bd_business_line_trip.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.create_by
     *
     * @param createBy the value for bd_business_line_trip.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.create_time
     *
     * @return the value of bd_business_line_trip.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.create_time
     *
     * @param createTime the value for bd_business_line_trip.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.update_by
     *
     * @return the value of bd_business_line_trip.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.update_by
     *
     * @param updateBy the value for bd_business_line_trip.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.update_time
     *
     * @return the value of bd_business_line_trip.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.update_time
     *
     * @param updateTime the value for bd_business_line_trip.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip.deleted
     *
     * @return the value of bd_business_line_trip.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip.deleted
     *
     * @param deleted the value for bd_business_line_trip.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}