package com.bdtrip.mobile.line.entity;

import java.util.Date;

public class LineTripContentEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.content_id
     *
     * @mbggenerated
     */
    private Long contentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.trip_id
     *
     * @mbggenerated
     */
    private Long tripId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.subtitle
     *
     * @mbggenerated
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.pic_template
     *
     * @mbggenerated
     */
    private Integer picTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.content_type
     *
     * @mbggenerated
     */
    private Integer contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_trip_content.trip_content
     *
     * @mbggenerated
     */
    private String tripContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.content_id
     *
     * @return the value of bd_business_line_trip_content.content_id
     *
     * @mbggenerated
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.content_id
     *
     * @param contentId the value for bd_business_line_trip_content.content_id
     *
     * @mbggenerated
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.trip_id
     *
     * @return the value of bd_business_line_trip_content.trip_id
     *
     * @mbggenerated
     */
    public Long getTripId() {
        return tripId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.trip_id
     *
     * @param tripId the value for bd_business_line_trip_content.trip_id
     *
     * @mbggenerated
     */
    public void setTripId(Long tripId) {
        this.tripId = tripId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.subtitle
     *
     * @return the value of bd_business_line_trip_content.subtitle
     *
     * @mbggenerated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.subtitle
     *
     * @param subtitle the value for bd_business_line_trip_content.subtitle
     *
     * @mbggenerated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.pic_template
     *
     * @return the value of bd_business_line_trip_content.pic_template
     *
     * @mbggenerated
     */
    public Integer getPicTemplate() {
        return picTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.pic_template
     *
     * @param picTemplate the value for bd_business_line_trip_content.pic_template
     *
     * @mbggenerated
     */
    public void setPicTemplate(Integer picTemplate) {
        this.picTemplate = picTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.content_type
     *
     * @return the value of bd_business_line_trip_content.content_type
     *
     * @mbggenerated
     */
    public Integer getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.content_type
     *
     * @param contentType the value for bd_business_line_trip_content.content_type
     *
     * @mbggenerated
     */
    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.create_by
     *
     * @return the value of bd_business_line_trip_content.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.create_by
     *
     * @param createBy the value for bd_business_line_trip_content.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.create_time
     *
     * @return the value of bd_business_line_trip_content.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.create_time
     *
     * @param createTime the value for bd_business_line_trip_content.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.update_by
     *
     * @return the value of bd_business_line_trip_content.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.update_by
     *
     * @param updateBy the value for bd_business_line_trip_content.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.update_time
     *
     * @return the value of bd_business_line_trip_content.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.update_time
     *
     * @param updateTime the value for bd_business_line_trip_content.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.deleted
     *
     * @return the value of bd_business_line_trip_content.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.deleted
     *
     * @param deleted the value for bd_business_line_trip_content.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_trip_content.trip_content
     *
     * @return the value of bd_business_line_trip_content.trip_content
     *
     * @mbggenerated
     */
    public String getTripContent() {
        return tripContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_trip_content.trip_content
     *
     * @param tripContent the value for bd_business_line_trip_content.trip_content
     *
     * @mbggenerated
     */
    public void setTripContent(String tripContent) {
        this.tripContent = tripContent;
    }
}