package com.bdtrip.mobile.line.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LineInfoEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public LineInfoEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLineIdIsNull() {
            addCriterion("line_id is null");
            return (Criteria) this;
        }

        public Criteria andLineIdIsNotNull() {
            addCriterion("line_id is not null");
            return (Criteria) this;
        }

        public Criteria andLineIdEqualTo(Long value) {
            addCriterion("line_id =", value, "lineId");
            return (Criteria) this;
        }

        public Criteria andLineIdNotEqualTo(Long value) {
            addCriterion("line_id <>", value, "lineId");
            return (Criteria) this;
        }

        public Criteria andLineIdGreaterThan(Long value) {
            addCriterion("line_id >", value, "lineId");
            return (Criteria) this;
        }

        public Criteria andLineIdGreaterThanOrEqualTo(Long value) {
            addCriterion("line_id >=", value, "lineId");
            return (Criteria) this;
        }

        public Criteria andLineIdLessThan(Long value) {
            addCriterion("line_id <", value, "lineId");
            return (Criteria) this;
        }

        public Criteria andLineIdLessThanOrEqualTo(Long value) {
            addCriterion("line_id <=", value, "lineId");
            return (Criteria) this;
        }

        public Criteria andLineIdIn(List<Long> values) {
            addCriterion("line_id in", values, "lineId");
            return (Criteria) this;
        }

        public Criteria andLineIdNotIn(List<Long> values) {
            addCriterion("line_id not in", values, "lineId");
            return (Criteria) this;
        }

        public Criteria andLineIdBetween(Long value1, Long value2) {
            addCriterion("line_id between", value1, value2, "lineId");
            return (Criteria) this;
        }

        public Criteria andLineIdNotBetween(Long value1, Long value2) {
            addCriterion("line_id not between", value1, value2, "lineId");
            return (Criteria) this;
        }

        public Criteria andLineSellingIsNull() {
            addCriterion("line_selling is null");
            return (Criteria) this;
        }

        public Criteria andLineSellingIsNotNull() {
            addCriterion("line_selling is not null");
            return (Criteria) this;
        }

        public Criteria andLineSellingEqualTo(Integer value) {
            addCriterion("line_selling =", value, "lineSelling");
            return (Criteria) this;
        }

        public Criteria andLineSellingNotEqualTo(Integer value) {
            addCriterion("line_selling <>", value, "lineSelling");
            return (Criteria) this;
        }

        public Criteria andLineSellingGreaterThan(Integer value) {
            addCriterion("line_selling >", value, "lineSelling");
            return (Criteria) this;
        }

        public Criteria andLineSellingGreaterThanOrEqualTo(Integer value) {
            addCriterion("line_selling >=", value, "lineSelling");
            return (Criteria) this;
        }

        public Criteria andLineSellingLessThan(Integer value) {
            addCriterion("line_selling <", value, "lineSelling");
            return (Criteria) this;
        }

        public Criteria andLineSellingLessThanOrEqualTo(Integer value) {
            addCriterion("line_selling <=", value, "lineSelling");
            return (Criteria) this;
        }

        public Criteria andLineSellingIn(List<Integer> values) {
            addCriterion("line_selling in", values, "lineSelling");
            return (Criteria) this;
        }

        public Criteria andLineSellingNotIn(List<Integer> values) {
            addCriterion("line_selling not in", values, "lineSelling");
            return (Criteria) this;
        }

        public Criteria andLineSellingBetween(Integer value1, Integer value2) {
            addCriterion("line_selling between", value1, value2, "lineSelling");
            return (Criteria) this;
        }

        public Criteria andLineSellingNotBetween(Integer value1, Integer value2) {
            addCriterion("line_selling not between", value1, value2, "lineSelling");
            return (Criteria) this;
        }

        public Criteria andLineTemplateIsNull() {
            addCriterion("line_template is null");
            return (Criteria) this;
        }

        public Criteria andLineTemplateIsNotNull() {
            addCriterion("line_template is not null");
            return (Criteria) this;
        }

        public Criteria andLineTemplateEqualTo(Integer value) {
            addCriterion("line_template =", value, "lineTemplate");
            return (Criteria) this;
        }

        public Criteria andLineTemplateNotEqualTo(Integer value) {
            addCriterion("line_template <>", value, "lineTemplate");
            return (Criteria) this;
        }

        public Criteria andLineTemplateGreaterThan(Integer value) {
            addCriterion("line_template >", value, "lineTemplate");
            return (Criteria) this;
        }

        public Criteria andLineTemplateGreaterThanOrEqualTo(Integer value) {
            addCriterion("line_template >=", value, "lineTemplate");
            return (Criteria) this;
        }

        public Criteria andLineTemplateLessThan(Integer value) {
            addCriterion("line_template <", value, "lineTemplate");
            return (Criteria) this;
        }

        public Criteria andLineTemplateLessThanOrEqualTo(Integer value) {
            addCriterion("line_template <=", value, "lineTemplate");
            return (Criteria) this;
        }

        public Criteria andLineTemplateIn(List<Integer> values) {
            addCriterion("line_template in", values, "lineTemplate");
            return (Criteria) this;
        }

        public Criteria andLineTemplateNotIn(List<Integer> values) {
            addCriterion("line_template not in", values, "lineTemplate");
            return (Criteria) this;
        }

        public Criteria andLineTemplateBetween(Integer value1, Integer value2) {
            addCriterion("line_template between", value1, value2, "lineTemplate");
            return (Criteria) this;
        }

        public Criteria andLineTemplateNotBetween(Integer value1, Integer value2) {
            addCriterion("line_template not between", value1, value2, "lineTemplate");
            return (Criteria) this;
        }

        public Criteria andLineTypeIsNull() {
            addCriterion("line_type is null");
            return (Criteria) this;
        }

        public Criteria andLineTypeIsNotNull() {
            addCriterion("line_type is not null");
            return (Criteria) this;
        }

        public Criteria andLineTypeEqualTo(Integer value) {
            addCriterion("line_type =", value, "lineType");
            return (Criteria) this;
        }

        public Criteria andLineTypeNotEqualTo(Integer value) {
            addCriterion("line_type <>", value, "lineType");
            return (Criteria) this;
        }

        public Criteria andLineTypeGreaterThan(Integer value) {
            addCriterion("line_type >", value, "lineType");
            return (Criteria) this;
        }

        public Criteria andLineTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("line_type >=", value, "lineType");
            return (Criteria) this;
        }

        public Criteria andLineTypeLessThan(Integer value) {
            addCriterion("line_type <", value, "lineType");
            return (Criteria) this;
        }

        public Criteria andLineTypeLessThanOrEqualTo(Integer value) {
            addCriterion("line_type <=", value, "lineType");
            return (Criteria) this;
        }

        public Criteria andLineTypeIn(List<Integer> values) {
            addCriterion("line_type in", values, "lineType");
            return (Criteria) this;
        }

        public Criteria andLineTypeNotIn(List<Integer> values) {
            addCriterion("line_type not in", values, "lineType");
            return (Criteria) this;
        }

        public Criteria andLineTypeBetween(Integer value1, Integer value2) {
            addCriterion("line_type between", value1, value2, "lineType");
            return (Criteria) this;
        }

        public Criteria andLineTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("line_type not between", value1, value2, "lineType");
            return (Criteria) this;
        }

        public Criteria andTravelTypeIsNull() {
            addCriterion("travel_type is null");
            return (Criteria) this;
        }

        public Criteria andTravelTypeIsNotNull() {
            addCriterion("travel_type is not null");
            return (Criteria) this;
        }

        public Criteria andTravelTypeEqualTo(Integer value) {
            addCriterion("travel_type =", value, "travelType");
            return (Criteria) this;
        }

        public Criteria andTravelTypeNotEqualTo(Integer value) {
            addCriterion("travel_type <>", value, "travelType");
            return (Criteria) this;
        }

        public Criteria andTravelTypeGreaterThan(Integer value) {
            addCriterion("travel_type >", value, "travelType");
            return (Criteria) this;
        }

        public Criteria andTravelTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("travel_type >=", value, "travelType");
            return (Criteria) this;
        }

        public Criteria andTravelTypeLessThan(Integer value) {
            addCriterion("travel_type <", value, "travelType");
            return (Criteria) this;
        }

        public Criteria andTravelTypeLessThanOrEqualTo(Integer value) {
            addCriterion("travel_type <=", value, "travelType");
            return (Criteria) this;
        }

        public Criteria andTravelTypeIn(List<Integer> values) {
            addCriterion("travel_type in", values, "travelType");
            return (Criteria) this;
        }

        public Criteria andTravelTypeNotIn(List<Integer> values) {
            addCriterion("travel_type not in", values, "travelType");
            return (Criteria) this;
        }

        public Criteria andTravelTypeBetween(Integer value1, Integer value2) {
            addCriterion("travel_type between", value1, value2, "travelType");
            return (Criteria) this;
        }

        public Criteria andTravelTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("travel_type not between", value1, value2, "travelType");
            return (Criteria) this;
        }

        public Criteria andStartPlaceIsNull() {
            addCriterion("start_place is null");
            return (Criteria) this;
        }

        public Criteria andStartPlaceIsNotNull() {
            addCriterion("start_place is not null");
            return (Criteria) this;
        }

        public Criteria andStartPlaceEqualTo(String value) {
            addCriterion("start_place =", value, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceNotEqualTo(String value) {
            addCriterion("start_place <>", value, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceGreaterThan(String value) {
            addCriterion("start_place >", value, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("start_place >=", value, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceLessThan(String value) {
            addCriterion("start_place <", value, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceLessThanOrEqualTo(String value) {
            addCriterion("start_place <=", value, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceLike(String value) {
            addCriterion("start_place like", value, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceNotLike(String value) {
            addCriterion("start_place not like", value, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceIn(List<String> values) {
            addCriterion("start_place in", values, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceNotIn(List<String> values) {
            addCriterion("start_place not in", values, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceBetween(String value1, String value2) {
            addCriterion("start_place between", value1, value2, "startPlace");
            return (Criteria) this;
        }

        public Criteria andStartPlaceNotBetween(String value1, String value2) {
            addCriterion("start_place not between", value1, value2, "startPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceIsNull() {
            addCriterion("end_place is null");
            return (Criteria) this;
        }

        public Criteria andEndPlaceIsNotNull() {
            addCriterion("end_place is not null");
            return (Criteria) this;
        }

        public Criteria andEndPlaceEqualTo(String value) {
            addCriterion("end_place =", value, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceNotEqualTo(String value) {
            addCriterion("end_place <>", value, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceGreaterThan(String value) {
            addCriterion("end_place >", value, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("end_place >=", value, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceLessThan(String value) {
            addCriterion("end_place <", value, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceLessThanOrEqualTo(String value) {
            addCriterion("end_place <=", value, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceLike(String value) {
            addCriterion("end_place like", value, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceNotLike(String value) {
            addCriterion("end_place not like", value, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceIn(List<String> values) {
            addCriterion("end_place in", values, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceNotIn(List<String> values) {
            addCriterion("end_place not in", values, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceBetween(String value1, String value2) {
            addCriterion("end_place between", value1, value2, "endPlace");
            return (Criteria) this;
        }

        public Criteria andEndPlaceNotBetween(String value1, String value2) {
            addCriterion("end_place not between", value1, value2, "endPlace");
            return (Criteria) this;
        }

        public Criteria andTripDayIsNull() {
            addCriterion("trip_day is null");
            return (Criteria) this;
        }

        public Criteria andTripDayIsNotNull() {
            addCriterion("trip_day is not null");
            return (Criteria) this;
        }

        public Criteria andTripDayEqualTo(Integer value) {
            addCriterion("trip_day =", value, "tripDay");
            return (Criteria) this;
        }

        public Criteria andTripDayNotEqualTo(Integer value) {
            addCriterion("trip_day <>", value, "tripDay");
            return (Criteria) this;
        }

        public Criteria andTripDayGreaterThan(Integer value) {
            addCriterion("trip_day >", value, "tripDay");
            return (Criteria) this;
        }

        public Criteria andTripDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("trip_day >=", value, "tripDay");
            return (Criteria) this;
        }

        public Criteria andTripDayLessThan(Integer value) {
            addCriterion("trip_day <", value, "tripDay");
            return (Criteria) this;
        }

        public Criteria andTripDayLessThanOrEqualTo(Integer value) {
            addCriterion("trip_day <=", value, "tripDay");
            return (Criteria) this;
        }

        public Criteria andTripDayIn(List<Integer> values) {
            addCriterion("trip_day in", values, "tripDay");
            return (Criteria) this;
        }

        public Criteria andTripDayNotIn(List<Integer> values) {
            addCriterion("trip_day not in", values, "tripDay");
            return (Criteria) this;
        }

        public Criteria andTripDayBetween(Integer value1, Integer value2) {
            addCriterion("trip_day between", value1, value2, "tripDay");
            return (Criteria) this;
        }

        public Criteria andTripDayNotBetween(Integer value1, Integer value2) {
            addCriterion("trip_day not between", value1, value2, "tripDay");
            return (Criteria) this;
        }

        public Criteria andTripNightIsNull() {
            addCriterion("trip_night is null");
            return (Criteria) this;
        }

        public Criteria andTripNightIsNotNull() {
            addCriterion("trip_night is not null");
            return (Criteria) this;
        }

        public Criteria andTripNightEqualTo(Integer value) {
            addCriterion("trip_night =", value, "tripNight");
            return (Criteria) this;
        }

        public Criteria andTripNightNotEqualTo(Integer value) {
            addCriterion("trip_night <>", value, "tripNight");
            return (Criteria) this;
        }

        public Criteria andTripNightGreaterThan(Integer value) {
            addCriterion("trip_night >", value, "tripNight");
            return (Criteria) this;
        }

        public Criteria andTripNightGreaterThanOrEqualTo(Integer value) {
            addCriterion("trip_night >=", value, "tripNight");
            return (Criteria) this;
        }

        public Criteria andTripNightLessThan(Integer value) {
            addCriterion("trip_night <", value, "tripNight");
            return (Criteria) this;
        }

        public Criteria andTripNightLessThanOrEqualTo(Integer value) {
            addCriterion("trip_night <=", value, "tripNight");
            return (Criteria) this;
        }

        public Criteria andTripNightIn(List<Integer> values) {
            addCriterion("trip_night in", values, "tripNight");
            return (Criteria) this;
        }

        public Criteria andTripNightNotIn(List<Integer> values) {
            addCriterion("trip_night not in", values, "tripNight");
            return (Criteria) this;
        }

        public Criteria andTripNightBetween(Integer value1, Integer value2) {
            addCriterion("trip_night between", value1, value2, "tripNight");
            return (Criteria) this;
        }

        public Criteria andTripNightNotBetween(Integer value1, Integer value2) {
            addCriterion("trip_night not between", value1, value2, "tripNight");
            return (Criteria) this;
        }

        public Criteria andLineNameIsNull() {
            addCriterion("line_name is null");
            return (Criteria) this;
        }

        public Criteria andLineNameIsNotNull() {
            addCriterion("line_name is not null");
            return (Criteria) this;
        }

        public Criteria andLineNameEqualTo(String value) {
            addCriterion("line_name =", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameNotEqualTo(String value) {
            addCriterion("line_name <>", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameGreaterThan(String value) {
            addCriterion("line_name >", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameGreaterThanOrEqualTo(String value) {
            addCriterion("line_name >=", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameLessThan(String value) {
            addCriterion("line_name <", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameLessThanOrEqualTo(String value) {
            addCriterion("line_name <=", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameLike(String value) {
            addCriterion("line_name like", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameNotLike(String value) {
            addCriterion("line_name not like", value, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameIn(List<String> values) {
            addCriterion("line_name in", values, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameNotIn(List<String> values) {
            addCriterion("line_name not in", values, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameBetween(String value1, String value2) {
            addCriterion("line_name between", value1, value2, "lineName");
            return (Criteria) this;
        }

        public Criteria andLineNameNotBetween(String value1, String value2) {
            addCriterion("line_name not between", value1, value2, "lineName");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeIsNull() {
            addCriterion("feature_type is null");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeIsNotNull() {
            addCriterion("feature_type is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeEqualTo(Integer value) {
            addCriterion("feature_type =", value, "featureType");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeNotEqualTo(Integer value) {
            addCriterion("feature_type <>", value, "featureType");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeGreaterThan(Integer value) {
            addCriterion("feature_type >", value, "featureType");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("feature_type >=", value, "featureType");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeLessThan(Integer value) {
            addCriterion("feature_type <", value, "featureType");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeLessThanOrEqualTo(Integer value) {
            addCriterion("feature_type <=", value, "featureType");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeIn(List<Integer> values) {
            addCriterion("feature_type in", values, "featureType");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeNotIn(List<Integer> values) {
            addCriterion("feature_type not in", values, "featureType");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeBetween(Integer value1, Integer value2) {
            addCriterion("feature_type between", value1, value2, "featureType");
            return (Criteria) this;
        }

        public Criteria andFeatureTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("feature_type not between", value1, value2, "featureType");
            return (Criteria) this;
        }

        public Criteria andRecommendIsNull() {
            addCriterion("recommend is null");
            return (Criteria) this;
        }

        public Criteria andRecommendIsNotNull() {
            addCriterion("recommend is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendEqualTo(Integer value) {
            addCriterion("recommend =", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendNotEqualTo(Integer value) {
            addCriterion("recommend <>", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendGreaterThan(Integer value) {
            addCriterion("recommend >", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendGreaterThanOrEqualTo(Integer value) {
            addCriterion("recommend >=", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendLessThan(Integer value) {
            addCriterion("recommend <", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendLessThanOrEqualTo(Integer value) {
            addCriterion("recommend <=", value, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendIn(List<Integer> values) {
            addCriterion("recommend in", values, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendNotIn(List<Integer> values) {
            addCriterion("recommend not in", values, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendBetween(Integer value1, Integer value2) {
            addCriterion("recommend between", value1, value2, "recommend");
            return (Criteria) this;
        }

        public Criteria andRecommendNotBetween(Integer value1, Integer value2) {
            addCriterion("recommend not between", value1, value2, "recommend");
            return (Criteria) this;
        }

        public Criteria andHeadPictureIsNull() {
            addCriterion("head_picture is null");
            return (Criteria) this;
        }

        public Criteria andHeadPictureIsNotNull() {
            addCriterion("head_picture is not null");
            return (Criteria) this;
        }

        public Criteria andHeadPictureEqualTo(String value) {
            addCriterion("head_picture =", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureNotEqualTo(String value) {
            addCriterion("head_picture <>", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureGreaterThan(String value) {
            addCriterion("head_picture >", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureGreaterThanOrEqualTo(String value) {
            addCriterion("head_picture >=", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureLessThan(String value) {
            addCriterion("head_picture <", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureLessThanOrEqualTo(String value) {
            addCriterion("head_picture <=", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureLike(String value) {
            addCriterion("head_picture like", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureNotLike(String value) {
            addCriterion("head_picture not like", value, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureIn(List<String> values) {
            addCriterion("head_picture in", values, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureNotIn(List<String> values) {
            addCriterion("head_picture not in", values, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureBetween(String value1, String value2) {
            addCriterion("head_picture between", value1, value2, "headPicture");
            return (Criteria) this;
        }

        public Criteria andHeadPictureNotBetween(String value1, String value2) {
            addCriterion("head_picture not between", value1, value2, "headPicture");
            return (Criteria) this;
        }

        public Criteria andThumbnailIsNull() {
            addCriterion("thumbnail is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailIsNotNull() {
            addCriterion("thumbnail is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailEqualTo(String value) {
            addCriterion("thumbnail =", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotEqualTo(String value) {
            addCriterion("thumbnail <>", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailGreaterThan(String value) {
            addCriterion("thumbnail >", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailGreaterThanOrEqualTo(String value) {
            addCriterion("thumbnail >=", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLessThan(String value) {
            addCriterion("thumbnail <", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLessThanOrEqualTo(String value) {
            addCriterion("thumbnail <=", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailLike(String value) {
            addCriterion("thumbnail like", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotLike(String value) {
            addCriterion("thumbnail not like", value, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailIn(List<String> values) {
            addCriterion("thumbnail in", values, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotIn(List<String> values) {
            addCriterion("thumbnail not in", values, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailBetween(String value1, String value2) {
            addCriterion("thumbnail between", value1, value2, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andThumbnailNotBetween(String value1, String value2) {
            addCriterion("thumbnail not between", value1, value2, "thumbnail");
            return (Criteria) this;
        }

        public Criteria andSubtitleIsNull() {
            addCriterion("subtitle is null");
            return (Criteria) this;
        }

        public Criteria andSubtitleIsNotNull() {
            addCriterion("subtitle is not null");
            return (Criteria) this;
        }

        public Criteria andSubtitleEqualTo(String value) {
            addCriterion("subtitle =", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotEqualTo(String value) {
            addCriterion("subtitle <>", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleGreaterThan(String value) {
            addCriterion("subtitle >", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleGreaterThanOrEqualTo(String value) {
            addCriterion("subtitle >=", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLessThan(String value) {
            addCriterion("subtitle <", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLessThanOrEqualTo(String value) {
            addCriterion("subtitle <=", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLike(String value) {
            addCriterion("subtitle like", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotLike(String value) {
            addCriterion("subtitle not like", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleIn(List<String> values) {
            addCriterion("subtitle in", values, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotIn(List<String> values) {
            addCriterion("subtitle not in", values, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleBetween(String value1, String value2) {
            addCriterion("subtitle between", value1, value2, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotBetween(String value1, String value2) {
            addCriterion("subtitle not between", value1, value2, "subtitle");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Integer value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Integer value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Integer value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Integer value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Integer value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Integer> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Integer> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Integer value1, Integer value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusIsNull() {
            addCriterion("online_status is null");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusIsNotNull() {
            addCriterion("online_status is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusEqualTo(Integer value) {
            addCriterion("online_status =", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusNotEqualTo(Integer value) {
            addCriterion("online_status <>", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusGreaterThan(Integer value) {
            addCriterion("online_status >", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("online_status >=", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusLessThan(Integer value) {
            addCriterion("online_status <", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusLessThanOrEqualTo(Integer value) {
            addCriterion("online_status <=", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusIn(List<Integer> values) {
            addCriterion("online_status in", values, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusNotIn(List<Integer> values) {
            addCriterion("online_status not in", values, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusBetween(Integer value1, Integer value2) {
            addCriterion("online_status between", value1, value2, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("online_status not between", value1, value2, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(Integer value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(Integer value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(Integer value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(Integer value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Integer value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<Integer> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<Integer> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(Integer value1, Integer value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(Integer value1, Integer value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(Integer value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(Integer value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(Integer value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(Integer value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(Integer value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<Integer> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<Integer> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(Integer value1, Integer value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(Integer value1, Integer value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bd_business_line_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bd_business_line_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}