package com.bdtrip.mobile.line.entity;

import java.util.Date;

public class LineInfoEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.line_id
     *
     * @mbggenerated
     */
    private Long lineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.line_selling
     *
     * @mbggenerated
     */
    private Integer lineSelling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.line_template
     *
     * @mbggenerated
     */
    private Integer lineTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.line_type
     *
     * @mbggenerated
     */
    private Integer lineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.travel_type
     *
     * @mbggenerated
     */
    private Integer travelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.start_place
     *
     * @mbggenerated
     */
    private String startPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.end_place
     *
     * @mbggenerated
     */
    private String endPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.trip_day
     *
     * @mbggenerated
     */
    private Integer tripDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.trip_night
     *
     * @mbggenerated
     */
    private Integer tripNight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.line_name
     *
     * @mbggenerated
     */
    private String lineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.feature_type
     *
     * @mbggenerated
     */
    private Integer featureType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.recommend
     *
     * @mbggenerated
     */
    private Integer recommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.head_picture
     *
     * @mbggenerated
     */
    private String headPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.thumbnail
     *
     * @mbggenerated
     */
    private String thumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.subtitle
     *
     * @mbggenerated
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.audit_status
     *
     * @mbggenerated
     */
    private Integer auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.online_status
     *
     * @mbggenerated
     */
    private Integer onlineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_line_info.feature_content
     *
     * @mbggenerated
     */
    private String featureContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.line_id
     *
     * @return the value of bd_business_line_info.line_id
     *
     * @mbggenerated
     */
    public Long getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.line_id
     *
     * @param lineId the value for bd_business_line_info.line_id
     *
     * @mbggenerated
     */
    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.line_selling
     *
     * @return the value of bd_business_line_info.line_selling
     *
     * @mbggenerated
     */
    public Integer getLineSelling() {
        return lineSelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.line_selling
     *
     * @param lineSelling the value for bd_business_line_info.line_selling
     *
     * @mbggenerated
     */
    public void setLineSelling(Integer lineSelling) {
        this.lineSelling = lineSelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.line_template
     *
     * @return the value of bd_business_line_info.line_template
     *
     * @mbggenerated
     */
    public Integer getLineTemplate() {
        return lineTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.line_template
     *
     * @param lineTemplate the value for bd_business_line_info.line_template
     *
     * @mbggenerated
     */
    public void setLineTemplate(Integer lineTemplate) {
        this.lineTemplate = lineTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.line_type
     *
     * @return the value of bd_business_line_info.line_type
     *
     * @mbggenerated
     */
    public Integer getLineType() {
        return lineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.line_type
     *
     * @param lineType the value for bd_business_line_info.line_type
     *
     * @mbggenerated
     */
    public void setLineType(Integer lineType) {
        this.lineType = lineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.travel_type
     *
     * @return the value of bd_business_line_info.travel_type
     *
     * @mbggenerated
     */
    public Integer getTravelType() {
        return travelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.travel_type
     *
     * @param travelType the value for bd_business_line_info.travel_type
     *
     * @mbggenerated
     */
    public void setTravelType(Integer travelType) {
        this.travelType = travelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.start_place
     *
     * @return the value of bd_business_line_info.start_place
     *
     * @mbggenerated
     */
    public String getStartPlace() {
        return startPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.start_place
     *
     * @param startPlace the value for bd_business_line_info.start_place
     *
     * @mbggenerated
     */
    public void setStartPlace(String startPlace) {
        this.startPlace = startPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.end_place
     *
     * @return the value of bd_business_line_info.end_place
     *
     * @mbggenerated
     */
    public String getEndPlace() {
        return endPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.end_place
     *
     * @param endPlace the value for bd_business_line_info.end_place
     *
     * @mbggenerated
     */
    public void setEndPlace(String endPlace) {
        this.endPlace = endPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.trip_day
     *
     * @return the value of bd_business_line_info.trip_day
     *
     * @mbggenerated
     */
    public Integer getTripDay() {
        return tripDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.trip_day
     *
     * @param tripDay the value for bd_business_line_info.trip_day
     *
     * @mbggenerated
     */
    public void setTripDay(Integer tripDay) {
        this.tripDay = tripDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.trip_night
     *
     * @return the value of bd_business_line_info.trip_night
     *
     * @mbggenerated
     */
    public Integer getTripNight() {
        return tripNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.trip_night
     *
     * @param tripNight the value for bd_business_line_info.trip_night
     *
     * @mbggenerated
     */
    public void setTripNight(Integer tripNight) {
        this.tripNight = tripNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.line_name
     *
     * @return the value of bd_business_line_info.line_name
     *
     * @mbggenerated
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.line_name
     *
     * @param lineName the value for bd_business_line_info.line_name
     *
     * @mbggenerated
     */
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.feature_type
     *
     * @return the value of bd_business_line_info.feature_type
     *
     * @mbggenerated
     */
    public Integer getFeatureType() {
        return featureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.feature_type
     *
     * @param featureType the value for bd_business_line_info.feature_type
     *
     * @mbggenerated
     */
    public void setFeatureType(Integer featureType) {
        this.featureType = featureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.recommend
     *
     * @return the value of bd_business_line_info.recommend
     *
     * @mbggenerated
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.recommend
     *
     * @param recommend the value for bd_business_line_info.recommend
     *
     * @mbggenerated
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.head_picture
     *
     * @return the value of bd_business_line_info.head_picture
     *
     * @mbggenerated
     */
    public String getHeadPicture() {
        return headPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.head_picture
     *
     * @param headPicture the value for bd_business_line_info.head_picture
     *
     * @mbggenerated
     */
    public void setHeadPicture(String headPicture) {
        this.headPicture = headPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.thumbnail
     *
     * @return the value of bd_business_line_info.thumbnail
     *
     * @mbggenerated
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.thumbnail
     *
     * @param thumbnail the value for bd_business_line_info.thumbnail
     *
     * @mbggenerated
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.subtitle
     *
     * @return the value of bd_business_line_info.subtitle
     *
     * @mbggenerated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.subtitle
     *
     * @param subtitle the value for bd_business_line_info.subtitle
     *
     * @mbggenerated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.audit_status
     *
     * @return the value of bd_business_line_info.audit_status
     *
     * @mbggenerated
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.audit_status
     *
     * @param auditStatus the value for bd_business_line_info.audit_status
     *
     * @mbggenerated
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.online_status
     *
     * @return the value of bd_business_line_info.online_status
     *
     * @mbggenerated
     */
    public Integer getOnlineStatus() {
        return onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.online_status
     *
     * @param onlineStatus the value for bd_business_line_info.online_status
     *
     * @mbggenerated
     */
    public void setOnlineStatus(Integer onlineStatus) {
        this.onlineStatus = onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.create_by
     *
     * @return the value of bd_business_line_info.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.create_by
     *
     * @param createBy the value for bd_business_line_info.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.create_time
     *
     * @return the value of bd_business_line_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.create_time
     *
     * @param createTime the value for bd_business_line_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.update_by
     *
     * @return the value of bd_business_line_info.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.update_by
     *
     * @param updateBy the value for bd_business_line_info.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.update_time
     *
     * @return the value of bd_business_line_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.update_time
     *
     * @param updateTime the value for bd_business_line_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.deleted
     *
     * @return the value of bd_business_line_info.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.deleted
     *
     * @param deleted the value for bd_business_line_info.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_line_info.feature_content
     *
     * @return the value of bd_business_line_info.feature_content
     *
     * @mbggenerated
     */
    public String getFeatureContent() {
        return featureContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_line_info.feature_content
     *
     * @param featureContent the value for bd_business_line_info.feature_content
     *
     * @mbggenerated
     */
    public void setFeatureContent(String featureContent) {
        this.featureContent = featureContent;
    }
}