package com.bdtrip.mobile.line.entity;

import java.util.Date;

public class TagsRelateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_tags_relate.relate_id
     *
     * @mbggenerated
     */
    private Long relateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_tags_relate.supplier_id
     *
     * @mbggenerated
     */
    private String supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_tags_relate.target_value
     *
     * @mbggenerated
     */
    private String targetValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_tags_relate.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_tags_relate.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_tags_relate.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_tags_relate.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_business_tags_relate.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_tags_relate.relate_id
     *
     * @return the value of bd_business_tags_relate.relate_id
     *
     * @mbggenerated
     */
    public Long getRelateId() {
        return relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_tags_relate.relate_id
     *
     * @param relateId the value for bd_business_tags_relate.relate_id
     *
     * @mbggenerated
     */
    public void setRelateId(Long relateId) {
        this.relateId = relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_tags_relate.supplier_id
     *
     * @return the value of bd_business_tags_relate.supplier_id
     *
     * @mbggenerated
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_tags_relate.supplier_id
     *
     * @param supplierId the value for bd_business_tags_relate.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_tags_relate.target_value
     *
     * @return the value of bd_business_tags_relate.target_value
     *
     * @mbggenerated
     */
    public String getTargetValue() {
        return targetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_tags_relate.target_value
     *
     * @param targetValue the value for bd_business_tags_relate.target_value
     *
     * @mbggenerated
     */
    public void setTargetValue(String targetValue) {
        this.targetValue = targetValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_tags_relate.create_by
     *
     * @return the value of bd_business_tags_relate.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_tags_relate.create_by
     *
     * @param createBy the value for bd_business_tags_relate.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_tags_relate.create_time
     *
     * @return the value of bd_business_tags_relate.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_tags_relate.create_time
     *
     * @param createTime the value for bd_business_tags_relate.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_tags_relate.update_by
     *
     * @return the value of bd_business_tags_relate.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_tags_relate.update_by
     *
     * @param updateBy the value for bd_business_tags_relate.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_tags_relate.update_time
     *
     * @return the value of bd_business_tags_relate.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_tags_relate.update_time
     *
     * @param updateTime the value for bd_business_tags_relate.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_business_tags_relate.deleted
     *
     * @return the value of bd_business_tags_relate.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_business_tags_relate.deleted
     *
     * @param deleted the value for bd_business_tags_relate.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}